[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
CSV        = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[compat]
Documenter = "≥0.26"
Plots = "≥1"
StatsPlots = "≥0.14"
CSV        = "≥0.8"
DataFrames = "≥1"
PrettyTables = "1, 2"
StatsBase = "≥0.33"
Distributions = "≥0.25"
CategoricalArrays = "≥0.9, 0.10"
